stages:
  - build
  - deploy

# Set variables for GitLab's container registry
variables:
  FRONTEND_IMAGE: $CI_REGISTRY_IMAGE/frontend:latest
  BACKEND_IMAGE: $CI_REGISTRY_IMAGE/backend:latest

# Authenticate with GitLab's container registry
before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin

# Build and push the frontend image
frontend-build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t $FRONTEND_IMAGE ./frontend
    - docker push $FRONTEND_IMAGE
  only:
    - main

# Build and push the backend image
backend-build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t $BACKEND_IMAGE ./backend
    - docker push $BACKEND_IMAGE
  only:
    - main

# Deployment Step
deploy:
  stage: deploy
  image: docker:latest  
  script:
    # Copy CI/CD variables into .env file
    - echo "VITE_BASE_URL=$VITE_BASE_URL" > .env
    - echo "MONGO_URI=$MONGO_URI" >> .env
    - echo "VITE_REACT_APP_GRAPHQL_URI=$VITE_REACT_APP_GRAPHQL_URI" >> .env
    - echo "JWT_SECRET=$JWT_SECRET" >> .env
    - echo "EMAIL_USER=$EMAIL_USER" >> .env
    - echo "EMAIL_PASS=$EMAIL_PASS" >> .env
    - echo "MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME" >> .env
    - echo "MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD" >> .env
    - echo "MONGO_USER=$MONGO_USER" >> .env
    - echo "MONGO_PASSWORD=$MONGO_PASSWORD" >> .env
    # Ensure SSH directory and decode SSH key securely
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - chmod 700 ~/.ssh
    
    # Debugging - Check the permissions and existence of the SSH key
    - ls -la ~/.ssh
    - cat ~/.ssh/id_rsa

    # Ensure the host's SSH fingerprint is trusted
    - ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts

    # Debugging - Test SSH connection
    - ssh -vvv $SSH_USER@$SSH_HOST
    # Securely copy the .env file to the remote server
    - scp .env $SSH_USER@$SSH_HOST:$WORK_DIR/.env

    - echo $WORK_DIR
    # Deploy services    
    - ssh $SSH_USER@$SSH_HOST "mkdir -p $WORK_DIR && cd $WORK_DIR && git pull origin main && docker-compose down && docker-compose up -d --build"

  only:
    - main
