stages:
  - build
  - deploy

# Set variables for GitLab's container registry
variables:
  FRONTEND_IMAGE: $CI_REGISTRY_IMAGE/frontend:latest
  BACKEND_IMAGE: $CI_REGISTRY_IMAGE/backend:latest

# Authenticate with GitLab's container registry
before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" $CI_REGISTRY --password-stdin

# Build and push the frontend image
frontend-build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t $FRONTEND_IMAGE ./frontend
    - docker push $FRONTEND_IMAGE
  only:
    - main

# Build and push the backend image
backend-build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t $BACKEND_IMAGE ./backend
    - docker push $BACKEND_IMAGE
  only:
    - main

# Deployment Step
deploy:
  stage: deploy
  image: docker:latest
  script:
    # Ensure SSH directory and decode SSH key
    - mkdir -p ~/.ssh && echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa    
    - chmod 700 ~/.ssh

    # Debugging SSH permissions
    - ls -la ~/.ssh
    - cat ~/.ssh/id_rsa

    # Allow host keys to avoid SSH prompts
    - ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts

    # SSH into server
    - ssh -vvv $SSH_USER@$SSH_HOST "mkdir -p $WORK_DIR && cd $WORK_DIR && git pull origin main && docker-compose down && docker-compose up -d --build"
  only:
    - main
