version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"     # Expose backend on port 4000
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"     # Expose frontend on port 5173 the defalut port of vite dev server
    depends_on:
      - backend         # Ensure backend is running before frontend
    env_file:
      - .env
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"   # Expose MongoDB
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
  nginx:
    image: nginx:stable-alpine                                                                                                                            
    volumes:                                                                                                                                              
      - ./nginx-config:/etc/nginx/conf.d                                                                                                                  
    ports:                                                                                                                                                
      - 80:80
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

volumes:
  mongo-data:
networks:
  app-network:
    driver: bridge